// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadiKeep.Logics.RdbContext;

#nullable disable

namespace RadiKeep.Logics.Migrations
{
    [DbContext(typeof(RadioDbContext))]
    [Migration("20260227150214_AddScheduleJobExecutionState")]
    partial class AddScheduleJobExecutionState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.AppConfiguration", b =>
                {
                    b.Property<string>("ConfigurationName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Val1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int?>("Val2")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<decimal?>("Val3")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("Val4")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.HasKey("ConfigurationName");

                    b.ToTable("AppConfigurations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.KeywordReserve", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(11);

                    b.Property<TimeSpan?>("EndDelay")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("ExcludedKeyword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsEnable")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsExcludeTitleOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<bool>("IsTitleOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("MergeTagBehavior")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(15);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(14);

                    b.Property<TimeSpan?>("StartDelay")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("KeywordReserve");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.KeywordReserveRadioStation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("RadioStation")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<int>("RadioServiceKind")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.HasKey("Id", "RadioStation");

                    b.HasIndex("Id");

                    b.ToTable("KeywordReserveRadioStations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.KeywordReserveTagRelation", b =>
                {
                    b.Property<string>("ReserveId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("ReserveId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("KeywordReserveTagRelations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.NhkRadiruProgram", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(9);

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<string>("OnDemandContentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("OnDemandExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(17);

                    b.Property<string>("Performer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<string>("ProgramUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.Property<DateOnly>("RadioDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.HasKey("ProgramId");

                    b.HasIndex("ProgramId", "StationId", "AreaId")
                        .IsUnique();

                    b.ToTable("NhkRadiruPrograms");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.NhkRadiruStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("AreaJpName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("DailyProgramApiUrlTemplate")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<string>("FmHls")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("ProgramDetailApiUrlTemplate")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("ProgramNowOnAirApiUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("R1Hls")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("R2Hls")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("AreaId", "ApiKey")
                        .IsUnique();

                    b.ToTable("NhkRadiruStations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.ProgramReserve", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<TimeSpan>("EndDelay")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<bool>("IsEnable")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsTimeFree")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(11);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.Property<int>("RadioServiceKind")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("RadioStationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<int>("ReservationType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<TimeSpan>("StartDelay")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<Guid?>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id", "ReservationType")
                        .IsUnique();

                    b.ToTable("ProgramReserve");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RadikoProgram", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<int>("AvailabilityTimeFree")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<string>("Performer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("ProgramUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<DateOnly>("RadioDate")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.HasKey("ProgramId");

                    b.HasIndex("ProgramId", "StationId")
                        .IsUnique();

                    b.ToTable("RadikoPrograms");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RadikoStation", b =>
                {
                    b.Property<string>("StationId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<bool>("AreaFree")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(9);

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<int>("RegionOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<int>("StationOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<bool>("TimeFree")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.HasKey("StationId");

                    b.ToTable("RadikoStations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.Recording", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(11);

                    b.Property<long>("EndDateTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsListened")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(14);

                    b.Property<bool>("IsTimeFree")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(8);

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<int>("ServiceKind")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(13);

                    b.Property<long>("StartDateTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(9);

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(12);

                    b.HasKey("Id");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingFile", b =>
                {
                    b.Property<string>("RecordingId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("FileRelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<bool>("HasHlsFile")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<string>("HlsDirectoryPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.HasKey("RecordingId");

                    b.ToTable("RecordingFiles");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingMetadata", b =>
                {
                    b.Property<string>("RecordingId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<string>("Performer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("ProgramUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.HasKey("RecordingId");

                    b.ToTable("RecordingMetadatas");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(4);

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(6);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(5);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("RecordingTags");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingTagRelation", b =>
                {
                    b.Property<string>("RecordingId")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("RecordingId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecordingTagRelations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.ScheduleJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<long?>("ActualStartUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(22);

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<long?>("CompletedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(23);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<long>("EndDateTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(11);

                    b.Property<TimeSpan?>("EndDelay")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(18);

                    b.Property<string>("KeywordReserveId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<int>("LastErrorCode")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(25);

                    b.Property<string>("LastErrorDetail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(26);

                    b.Property<string>("Performer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.Property<long>("PrepareStartUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(20);

                    b.Property<string>("ProgramId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<long?>("QueuedAtUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(21);

                    b.Property<int>("RecordingType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(16);

                    b.Property<int>("ReserveType")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(17);

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(24);

                    b.Property<int>("ServiceKind")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<long>("StartDateTime")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(10);

                    b.Property<TimeSpan?>("StartDelay")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<int>("State")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(19);

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<Guid?>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled", "State", "PrepareStartUtc")
                        .HasDatabaseName("IX_ScheduleJob_SchedulerScan");

                    b.HasIndex("ProgramId", "ServiceKind", "StartDateTime")
                        .IsUnique()
                        .HasDatabaseName("IX_ScheduleJob_Active_Unique")
                        .HasFilter("State IN (0, 1, 2, 3)");

                    b.ToTable("ScheduleJob");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.ScheduleJobKeywordReserveRelation", b =>
                {
                    b.Property<string>("ScheduleJobId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("KeywordReserveId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("ScheduleJobId", "KeywordReserveId");

                    b.HasIndex("KeywordReserveId");

                    b.ToTable("ScheduleJobKeywordReserveRelations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.KeywordReserveTagRelation", b =>
                {
                    b.HasOne("RadiKeep.Logics.RdbContext.KeywordReserve", "KeywordReserve")
                        .WithMany("KeywordReserveTagRelations")
                        .HasForeignKey("ReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiKeep.Logics.RdbContext.RecordingTag", "Tag")
                        .WithMany("KeywordReserveTagRelations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeywordReserve");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingFile", b =>
                {
                    b.HasOne("RadiKeep.Logics.RdbContext.Recording", "Recording")
                        .WithOne("RecordingFile")
                        .HasForeignKey("RadiKeep.Logics.RdbContext.RecordingFile", "RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingMetadata", b =>
                {
                    b.HasOne("RadiKeep.Logics.RdbContext.Recording", "Recording")
                        .WithOne("RecordingMetadata")
                        .HasForeignKey("RadiKeep.Logics.RdbContext.RecordingMetadata", "RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingTagRelation", b =>
                {
                    b.HasOne("RadiKeep.Logics.RdbContext.Recording", "Recording")
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiKeep.Logics.RdbContext.RecordingTag", "Tag")
                        .WithMany("RecordingTagRelations")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.ScheduleJobKeywordReserveRelation", b =>
                {
                    b.HasOne("RadiKeep.Logics.RdbContext.KeywordReserve", "KeywordReserve")
                        .WithMany("ScheduleJobRelations")
                        .HasForeignKey("KeywordReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadiKeep.Logics.RdbContext.ScheduleJob", "ScheduleJob")
                        .WithMany("KeywordReserveRelations")
                        .HasForeignKey("ScheduleJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeywordReserve");

                    b.Navigation("ScheduleJob");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.KeywordReserve", b =>
                {
                    b.Navigation("KeywordReserveTagRelations");

                    b.Navigation("ScheduleJobRelations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.Recording", b =>
                {
                    b.Navigation("RecordingFile");

                    b.Navigation("RecordingMetadata");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.RecordingTag", b =>
                {
                    b.Navigation("KeywordReserveTagRelations");

                    b.Navigation("RecordingTagRelations");
                });

            modelBuilder.Entity("RadiKeep.Logics.RdbContext.ScheduleJob", b =>
                {
                    b.Navigation("KeywordReserveRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
