using System.Globalization;
using System.Text;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using RadiKeep.Application;
using RadiKeep.DependencyInjection;
using RadiKeep.Endpoints;
using RadiKeep.Filters;
using RadiKeep.Features.Recording;
using RadiKeep.Features.Notification;
using RadiKeep.Features.General;
using RadiKeep.Hubs;
using RadiKeep.Features.Tag;
using RadiKeep.Features.Reserve;
using RadiKeep.Features.Program;
using RadiKeep.Features.Setting;
using RadiKeep.Logics.Infrastructure.Recording;
using RadiKeep.Logics.Logics;
using RadiKeep.Logics.RdbContext;
using RadiKeep.Logics.Services;
using ZLogger;


CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("ja-JP");
// 時間帯を日本時間に設定

var builder = WebApplication.CreateBuilder(args);
var localSettingsPath = Path.Combine(builder.Environment.ContentRootPath, "radikeep.settings.json");
var systemSettingsPath = "/etc/radikeep/radikeep.settings.json";
var autoGeneratedSettingsPath = EnsureLinuxSettingsFile(localSettingsPath, systemSettingsPath, builder.Environment.ContentRootPath);

if (OperatingSystem.IsLinux())
{
    builder.Host.UseSystemd();
}

// Add services to the container.
builder.Services.AddControllersWithViews(options =>
{
    options.Filters.Add<ApiExceptionFilter>();
});

// Configuration
var config = builder.Configuration;
config.AddJsonFile("radikeep.settings.json", optional: true, reloadOnChange: true);
config.AddJsonFile("/etc/radikeep/radikeep.settings.json", optional: true, reloadOnChange: true);
config.AddEnvironmentVariables();

// DB
builder.Services.AddDbDi(config, builder.Environment);

// Options
builder.Services.AddConfigDi(config);

// Logger
builder.Logging.AddLoggingDi(config);

// DataProtection
{
    var dataProtectionBuilder = builder.Services.AddDataProtection();

    if (!OperatingSystem.IsWindows())
    {
        var keysPath = config["RadiKeep:DataProtectionKeysPath"];
        if (string.IsNullOrWhiteSpace(keysPath))
        {
            keysPath = Path.Combine(builder.Environment.ContentRootPath, "keys");
        }

        Directory.CreateDirectory(keysPath);
        dataProtectionBuilder.PersistKeysToFileSystem(new DirectoryInfo(keysPath));
    }
}

// ServiceCollection
builder.Services.AddLogicDiCollection(config);

// for API
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddOpenApi();
builder.Services.AddSignalR();


var app = builder.Build();
if (!string.IsNullOrWhiteSpace(autoGeneratedSettingsPath))
{
    app.Logger.ZLogInformation($"設定ファイルが見つからなかったため、既定値で自動生成しました。 path={autoGeneratedSettingsPath}");
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<RadioDbContext>();
    await ApplyMigrationsWithBackupIfNeededAsync(context, app.Environment.ContentRootPath, app.Logger);
}

app.UseStaticFiles();

// HLS形式ファイル保存先
{
    // DIで格納したRadikoOptionsを取得
    var appConfigService = app.Services.GetRequiredService<IAppConfigurationService>();
    var hlsCacheRoot = TemporaryStoragePaths.GetHlsCacheRootDirectory(appConfigService.TemporaryFileSaveDir);
    Directory.CreateDirectory(hlsCacheRoot);

    app.UseStaticFiles(new StaticFileOptions
    {
        FileProvider = new PhysicalFileProvider(hlsCacheRoot),
        RequestPath = "/static"
    });
}

app.UseRouting();

app.UseAuthorization();

app.UseMiddleware<RequestLoggingScopeMiddleware>();

if (app.Environment.IsDevelopment())
{
    app.UseMemoryUsageMiddleware();
}

#pragma warning disable ASP0014
app.UseEndpoints(endpoints =>
{
    endpoints.MapApiEndpoints();
    endpoints.MapGeneralEndpoints();
    endpoints.MapProgramEndpoints();
    endpoints.MapSettingEndpoints();
    endpoints.MapExternalImportEndpoints();
    endpoints.MapRecordingEndpoints();
    endpoints.MapNotificationEndpoints();
    endpoints.MapTagEndpoints();
    endpoints.MapReserveEndpoints();
    endpoints.MapHub<RecordingHub>("/hubs/recordings");
    endpoints.MapHub<NotificationHub>("/hubs/notifications");
    endpoints.MapHub<ReserveHub>("/hubs/reserves");
    endpoints.MapHub<ProgramUpdateHub>("/hubs/program-updates");
    endpoints.MapHub<AppEventHub>("/hubs/app-events");
    endpoints.MapHub<RecordedDuplicateDetectionHub>("/hubs/duplicate-detection");

    endpoints.MapControllerRoute(
        name: "areas",
        pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}"
    );

    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
});
#pragma warning restore ASP0014

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();

    // TypeScriptマップ用
    app.UseFileServer(new FileServerOptions()
    {
        FileProvider = new PhysicalFileProvider(Path.Combine(app.Environment.ContentRootPath, "Scripts")),
        RequestPath = new PathString("/Scripts"),
    });
}


using (var scope = app.Services.CreateScope())
{
    var startupTask = scope.ServiceProvider.GetRequiredService<StartupTask>();
    await startupTask.InitializeAsync();
}

app.Run();

static string? EnsureLinuxSettingsFile(string localSettingsPath, string systemSettingsPath, string contentRootPath)
{
    if (!OperatingSystem.IsLinux())
    {
        return null;
    }

    if (File.Exists(localSettingsPath) || File.Exists(systemSettingsPath))
    {
        return null;
    }

    try
    {
        var samplePath = Path.Combine(contentRootPath, "radikeep.settings.sample.json");

        var payload = File.Exists(samplePath) ?
            File.ReadAllText(samplePath, Encoding.UTF8)
            : """
              {
                "RadiKeep": {
                  "RecordFileSaveFolder": "record",
                  "TemporaryFileSaveFolder": "temp"
                }
              }
              """;

        File.WriteAllText(localSettingsPath, payload, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return localSettingsPath;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"[RadiKeep] Linux設定ファイルの自動生成に失敗しました。 path={localSettingsPath} error={ex.Message}");
        return null;
    }
}

static async Task ApplyMigrationsWithBackupIfNeededAsync(
    RadioDbContext context,
    string contentRootPath,
    ILogger logger,
    CancellationToken cancellationToken = default)
{
    var pendingMigrations = (await context.Database.GetPendingMigrationsAsync(cancellationToken)).ToArray();
    if (pendingMigrations.Length == 0)
    {
        return;
    }

    TryBackupSqliteDatabaseFile(context, contentRootPath, pendingMigrations, logger);

    logger.ZLogInformation($"DBマイグレーションを実行します。 pendingCount={pendingMigrations.Length}");
    await context.Database.MigrateAsync(cancellationToken);
    logger.ZLogInformation($"DBマイグレーションが完了しました。");
}

static void TryBackupSqliteDatabaseFile(
    RadioDbContext context,
    string contentRootPath,
    IReadOnlyCollection<string> pendingMigrations,
    ILogger logger)
{
    var connectionString = context.Database.GetConnectionString();
    if (string.IsNullOrWhiteSpace(connectionString))
    {
        logger.ZLogWarning($"SQLite接続文字列が取得できなかったため、DBバックアップをスキップします。");
        return;
    }

    var dataSource = new SqliteConnectionStringBuilder(connectionString).DataSource;
    if (string.IsNullOrWhiteSpace(dataSource) || dataSource == ":memory:")
    {
        logger.ZLogWarning($"SQLiteのData Sourceがファイルではないため、DBバックアップをスキップします。");
        return;
    }

    var dbFilePath = Path.IsPathRooted(dataSource)
        ? dataSource
        : Path.GetFullPath(dataSource, contentRootPath);

    if (!File.Exists(dbFilePath))
    {
        logger.ZLogInformation($"SQLite DBファイルが未作成のため、バックアップをスキップします。 path={dbFilePath}");
        return;
    }

    var backupDir = Path.Combine(Path.GetDirectoryName(dbFilePath)!, "migration-backups");
    Directory.CreateDirectory(backupDir);

    var latestMigration = pendingMigrations.LastOrDefault() ?? "unknown";
    var backupFileName = $"{Path.GetFileNameWithoutExtension(dbFilePath)}.{DateTimeOffset.Now:yyyyMMdd_HHmmss}.before_{latestMigration}.db";
    var backupPath = Path.Combine(backupDir, backupFileName);

    using var sourceConnection = new SqliteConnection(connectionString);
    sourceConnection.Open();

    using var backupConnection = new SqliteConnection($"Data Source={backupPath};Mode=ReadWriteCreate");
    backupConnection.Open();

    sourceConnection.BackupDatabase(backupConnection);
    logger.ZLogInformation($"SQLite DBバックアップを作成しました。 path={backupPath}, pendingCount={pendingMigrations.Count}");

    PruneOldMigrationBackups(backupDir, Path.GetFileNameWithoutExtension(dbFilePath), keepCount: 2, logger);
}

static void PruneOldMigrationBackups(string backupDir, string dbFileBaseName, int keepCount, ILogger logger)
{
    if (keepCount < 1)
    {
        keepCount = 1;
    }

    var pattern = $"{dbFileBaseName}.*.before_*.db";
    var files = new DirectoryInfo(backupDir)
        .GetFiles(pattern, SearchOption.TopDirectoryOnly)
        .OrderByDescending(x => x.CreationTimeUtc)
        .ToList();

    var deleteTargets = files.Skip(keepCount).ToList();
    foreach (var file in deleteTargets)
    {
        try
        {
            file.Delete();
        }
        catch (Exception ex)
        {
            logger.ZLogWarning($"古いDBバックアップの削除に失敗しました。 path={file.FullName}, error={ex.Message}");
        }
    }
}

