using System.Globalization;
using System.Text;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using RadiKeep.Application;
using RadiKeep.DependencyInjection;
using RadiKeep.Filters;
using RadiKeep.Logics.Infrastructure.Recording;
using RadiKeep.Logics.Logics;
using RadiKeep.Logics.RdbContext;
using RadiKeep.Logics.Services;
using ZLogger;


CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("ja-JP");
// 時間帯を日本時間に設定

var builder = WebApplication.CreateBuilder(args);
var localSettingsPath = Path.Combine(builder.Environment.ContentRootPath, "radikeep.settings.json");
var systemSettingsPath = "/etc/radikeep/radikeep.settings.json";
var autoGeneratedSettingsPath = EnsureLinuxSettingsFile(localSettingsPath, systemSettingsPath, builder.Environment.ContentRootPath);

if (OperatingSystem.IsLinux())
{
    builder.Host.UseSystemd();
}

// Add services to the container.
builder.Services.AddControllersWithViews(options =>
{
    options.Filters.Add<ApiExceptionFilter>();
});

// Configuration
var config = builder.Configuration;
config.AddJsonFile("radikeep.settings.json", optional: true, reloadOnChange: true);
config.AddJsonFile("/etc/radikeep/radikeep.settings.json", optional: true, reloadOnChange: true);
config.AddEnvironmentVariables();

// DB
builder.Services.AddDbDi(config, builder.Environment);

// Options
builder.Services.AddConfigDi(config);

// Logger
builder.Logging.AddLoggingDi(config);

// DataProtection
{
    var keysPath = config["RadiKeep:DataProtectionKeysPath"];
    if (string.IsNullOrWhiteSpace(keysPath))
    {
        keysPath = Path.Combine(builder.Environment.ContentRootPath, "keys");
    }
    Directory.CreateDirectory(keysPath);
    builder.Services.AddDataProtection()
        .PersistKeysToFileSystem(new DirectoryInfo(keysPath));
}

// Quartz
builder.Services.AddQuartzDi(config);


// ServiceCollection
builder.Services.AddLogicDiCollection(config);

// for API
builder.Services.AddEndpointsApiExplorer();

#if DEBUG
builder.Services.AddSwaggerGen();
#endif


var app = builder.Build();
if (!string.IsNullOrWhiteSpace(autoGeneratedSettingsPath))
{
    app.Logger.ZLogInformation($"設定ファイルが見つからなかったため、既定値で自動生成しました。 path={autoGeneratedSettingsPath}");
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<RadioDbContext>();

    await context.Database.MigrateAsync(); // DBのマイグレーション
}

app.UseStaticFiles();

// HLS形式ファイル保存先
{
    // DIで格納したRadikoOptionsを取得
    var appConfigService = app.Services.GetRequiredService<IAppConfigurationService>();
    var hlsCacheRoot = TemporaryStoragePaths.GetHlsCacheRootDirectory(appConfigService.TemporaryFileSaveDir);
    Directory.CreateDirectory(hlsCacheRoot);

    app.UseStaticFiles(new StaticFileOptions
    {
        FileProvider = new PhysicalFileProvider(hlsCacheRoot),
        RequestPath = "/static"
    });
}


app.UseRouting();

app.UseAuthorization();

app.UseMiddleware<RequestLoggingScopeMiddleware>();

if (app.Environment.IsDevelopment())
{
    app.UseMemoryUsageMiddleware();
}

#pragma warning disable ASP0014
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllerRoute(
        name: "areas",
        pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}"
    );

    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
});
#pragma warning restore ASP0014

if (app.Environment.IsDevelopment())
{
#if DEBUG
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "RadiKeep API");
    });
#endif

    // TypeScriptマップ用
    app.UseFileServer(new FileServerOptions()
    {
        FileProvider = new PhysicalFileProvider(Path.Combine(app.Environment.ContentRootPath, "Scripts")),
        RequestPath = new PathString("/Scripts"),
    });
}


using (var scope = app.Services.CreateScope())
{
    var startupTask = scope.ServiceProvider.GetRequiredService<StartupTask>();
    await startupTask.InitializeAsync();
}

app.Run();

static string? EnsureLinuxSettingsFile(string localSettingsPath, string systemSettingsPath, string contentRootPath)
{
    if (!OperatingSystem.IsLinux())
    {
        return null;
    }

    if (File.Exists(localSettingsPath) || File.Exists(systemSettingsPath))
    {
        return null;
    }

    try
    {
        var samplePath = Path.Combine(contentRootPath, "radikeep.settings.sample.json");

        var payload = File.Exists(samplePath) ?
            File.ReadAllText(samplePath, Encoding.UTF8)
            : """
              {
                "RadiKeep": {
                  "RecordFileSaveFolder": "record",
                  "TemporaryFileSaveFolder": "temp"
                }
              }
              """;

        File.WriteAllText(localSettingsPath, payload, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        return localSettingsPath;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"[RadiKeep] Linux設定ファイルの自動生成に失敗しました。 path={localSettingsPath} error={ex.Message}");
        return null;
    }
}
